name: PlatformIO CI

on: [pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
          examples/chBlink
          # examples/chBlinkPrint,
          # examples/chContextTime,
          # examples/chCoop,
          # examples/chDataSharing,
          # examples/chEvent,
          # examples/chFifoDataLogger,
          # examples/chIsrSemaphore,
          # examples/chJitter,
          # examples/chMailbox,
          # examples/chMemPool,
          # examples/chMutex,
          # examples/chRoundRobin,
          # examples/chSemaphore
        ]
        board: [
          zero, uno, due, teensy30, teensy31, teensy35, teensy36, teensy40, teensy41
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --lib="." --board=${{ matrix.board }}
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}