name: PlatformIO CI

on:
  pull_request:
  repository_dispatch:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
        - { sketch: chBlink, board: zero }      # SAMD21G18A
        - { sketch: chBlink, board: uno }       # ATMEGA328P
        - { sketch: chBlink, board: due }       # AT91SAM3X8E
        # - { sketch: chBlink, board: nano_every } # ATMEGA4809
        - { sketch: chBlink, board: megaatmega2560 } # ATMEGA2560

        - { sketch: chBlink, board: teensy2 }   # ATMEGA32U4
        - { sketch: chBlink, board: teensy2pp } # AT90USB1286
        - { sketch: chBlink, board: teensy30 }  # MK20DX128
        - { sketch: chBlink, board: teensy31 }  # MK20DX256
        - { sketch: chBlink, board: teensy35 }  # MK64FX512
        - { sketch: chBlink, board: teensy36 }  # MK66FX1M0
        - { sketch: chBlink, board: teensy40 }  # IMXRT1062
        # - { sketch: chBlink, board: teensy41 }  # IMXRT1062

        - { sketch: chBlinkPrint,  board: teensy40 }
        - { sketch: chContextTime, board: teensy40 }
        - { sketch: chCoop,        board: teensy40 }
        - { sketch: chDataSharing, board: teensy40 }
        - { sketch: chEvent,       board: teensy40 }
        # - { sketch: chFifoDataLogger,board: teensy40 }
        - { sketch: chIsrSemaphore, board: teensy40 }
        - { sketch: chJitter,      board: teensy40 }
        - { sketch: chMailbox,     board: teensy40 }
        - { sketch: chMemPool,     board: teensy40 }
        - { sketch: chMutex,       board: teensy40 }
        - { sketch: chRoundRobin,  board: teensy40 }
        - { sketch: chSemaphore,   board: teensy40 }

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/pio-ci
      with:
        src: examples/${{ matrix.example.sketch }}
        board: ${{ matrix.example.board }}
