name: Arduino Compile Sketches

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: arduino/compile-sketches@v1
      with:
        fqbn: 'arduino:avr:zero'
